"""create all tables

Revision ID: 363b69709951
Revises: 0001
Create Date: 2026-09-01 08:59:34.552857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '363b69709951'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adherents',
    sa.Column('code_adherent', sa.String(length=20), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('matricule_fiscal', sa.String(length=50), nullable=True),
    sa.Column('statut_contrat', sa.Enum('ACTIF', 'RESILIE', 'SUSPENDU', name='statut_contrat', schema='imx'), nullable=False),
    sa.PrimaryKeyConstraint('code_adherent'),
    schema='imx'
    )
    op.create_table('debiteurs',
    sa.Column('code_debiteur', sa.String(length=20), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('rib', sa.String(length=20), nullable=False),
    sa.Column('code_adherent', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['code_adherent'], ['imx.adherents.code_adherent'], ),
    sa.PrimaryKeyConstraint('code_debiteur'),
    sa.UniqueConstraint('rib'),
    schema='imx'
    )
    op.create_table('factures',
    sa.Column('num_facture', sa.String(length=30), nullable=False),
    sa.Column('code_adherent', sa.String(length=20), nullable=False),
    sa.Column('code_debiteur', sa.String(length=20), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('montant_avoirs', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('montant_net', sa.Numeric(precision=14, scale=3), sa.Computed('montant_ttc - montant_avoirs', persisted=True), nullable=False),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('ENCOURS', 'PAYEE', 'ANNULEE', name='statut_facture', schema='imx'), nullable=False),
    sa.ForeignKeyConstraint(['code_adherent'], ['imx.adherents.code_adherent'], ),
    sa.ForeignKeyConstraint(['code_debiteur'], ['imx.debiteurs.code_debiteur'], ),
    sa.PrimaryKeyConstraint('num_facture'),
    schema='imx'
    )
    op.create_table('traites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero_lcn', sa.String(length=20), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('date_creation_traite', sa.Date(), nullable=False),
    sa.Column('date_reception', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('statut', sa.Enum('A_TRAITER', 'EN_COURS_OCR', 'ECARTS_A_TRAITER', 'CONTROLE_MANUEL_REQUIS', 'RENVOYEE', 'FRAUDE_SIGNALEE', 'VALIDEE', name='traite_statut'), nullable=False),
    sa.Column('code_adherent', sa.String(length=20), nullable=True),
    sa.Column('code_debiteur', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_adherent'], ['imx.adherents.code_adherent'], ),
    sa.ForeignKeyConstraint(['code_debiteur'], ['imx.debiteurs.code_debiteur'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_lcn')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('traite_id', sa.UUID(), nullable=True),
    sa.Column('utilisateur', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['traite_id'], ['traites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champs_extraits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('traite_id', sa.UUID(), nullable=False),
    sa.Column('nom_champ', sa.String(length=100), nullable=False),
    sa.Column('occurrence', sa.SmallInteger(), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('OCR', 'NLP', 'MANUEL', name='source_champ'), nullable=False),
    sa.Column('confiance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['traite_id'], ['traites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('traite_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('VALIDEE', 'RENVOI', 'FRAUDE', name='type_decision'), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('decide_par', sa.String(length=120), nullable=False),
    sa.Column('decide_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['traite_id'], ['traites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapprochements_nlp',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('traite_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('TIREUR', 'TIRE', 'ORDRE', name='role_nlp'), nullable=False),
    sa.Column('valeur_scan', sa.Text(), nullable=False),
    sa.Column('valeur_referentiel', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('code_adherent_matche', sa.String(length=20), nullable=True),
    sa.Column('code_debiteur_matche', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_adherent_matche'], ['imx.adherents.code_adherent'], ),
    sa.ForeignKeyConstraint(['code_debiteur_matche'], ['imx.debiteurs.code_debiteur'], ),
    sa.ForeignKeyConstraint(['traite_id'], ['traites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traite_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('traite_id', sa.UUID(), nullable=False),
    sa.Column('face', sa.Enum('RECTO', 'VERSO', name='face'), nullable=False),
    sa.Column('fichier_nom', sa.String(length=255), nullable=False),
    sa.Column('fichier_chemin', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['traite_id'], ['traites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traite_id', 'face', name='uq_traite_documents_traite_face')
    )
    op.create_table('verifications_manuelles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('traite_id', sa.UUID(), nullable=False),
    sa.Column('code_verification', sa.Enum('SIG_TIRE', 'ACCEPT', 'SIG_TIREUR', 'ENDOS', name='verification_code'), nullable=False),
    sa.Column('statut', sa.Enum('CONFORME', 'ANOMALIE', name='statut_verification'), nullable=True),
    sa.Column('verifie_par', sa.String(length=120), nullable=True),
    sa.Column('verifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['traite_id'], ['traites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traite_id', 'code_verification', name='uq_verif_manuelle_traite_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications_manuelles')
    op.drop_table('traite_documents')
    op.drop_table('rapprochements_nlp')
    op.drop_table('decisions')
    op.drop_table('champs_extraits')
    op.drop_table('audit_log')
    op.drop_table('traites')
    op.drop_table('factures', schema='imx')
    op.drop_table('debiteurs', schema='imx')
    op.drop_table('adherents', schema='imx')
    # ### end Alembic commands ###

    # Postgres ENUM types are not dropped automatically when the tables
    # using them are dropped (they could in principle be shared). Without
    # this, a downgrade-then-upgrade cycle fails the second time around with
    # "type already exists" — exactly what the test suite does every run.
    for enum_name, schema in [
        ("verification_code", None),
        ("face", None),
        ("role_nlp", None),
        ("type_decision", None),
        ("source_champ", None),
        ("traite_statut", None),
        ("statut_verification", None),
        ("statut_facture", "imx"),
        ("statut_contrat", "imx"),
    ]:
        qualified = f"{schema}.{enum_name}" if schema else enum_name
        op.execute(f"DROP TYPE IF EXISTS {qualified}")
