"""add document metadata

Revision ID: 530cfcd7d929
Revises: 363b69709951
Create Date: 2026-09-01 09:57:18.043283
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '530cfcd7d929'
down_revision: Union[str, None] = '363b69709951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traite_documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('traite_documents', sa.Column('taille_octets', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traite_documents', 'taille_octets')
    op.drop_column('traite_documents', 'content_type')
    # ### end Alembic commands ###
