"""montant_avoirs_saisi

Revision ID: b7f3a2c9e1d4
Revises: a4d8e1f6c2b9
Create Date: 2026-09-08 14:00:00.000000

BPMN Phase 3, étape 2 (Caissier) — "Saisir manuellement les montants des
avoirs par débiteur si applicable", feeding a future TR-112 coverage
calculation (still deferred). Deliberately a new column on this app's own
``traites`` table, not a write into ``imx.factures.montant_avoirs``: that
column belongs to the external IMX referential (see db/models/imx.py),
which production connects to read-only — see app/db/models/traite.py's
own docstring on this column for why a cashier's observation can't live
there.

Hand-written, not autogenerated (a single ``add_column``) — no
``extractions_ia`` false-positive to strip here (see 49a3fe136ee4's
docstring for that recurring caveat on autogenerated diffs specifically).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'b7f3a2c9e1d4'
down_revision: Union[str, None] = 'a4d8e1f6c2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('traites', sa.Column('montant_avoirs_saisi', sa.Numeric(precision=14, scale=3), nullable=True))


def downgrade() -> None:
    op.drop_column('traites', 'montant_avoirs_saisi')
