"""domiciliation_and_cross_field_discrepancies

Revision ID: d3f7a1c9b2e4
Revises: c8e4b6f2a3d7
Create Date: 2026-09-10 12:00:00.000000

Two real, already-computed values that were invisible to a reviewer:

1. domiciliation_texte is extracted by the VLM prompt (TR-122) but
   execute_analysis never read it from result.parties — nothing was
   persisted, nothing exposed. traites.domiciliation is where it lives now
   (see app/db/models/traite.py's own docstring on this column for why not
   a duplicated ChampExtrait field).
2. compute_inconsistencies (TR-111/TR-121/TR-122) computes 3 real
   cross-field écarts that block auto-confirm, but they were only ever
   written into audit_log.details["incoherences"] — never exposed by any
   GET endpoint. traites.cross_field_discrepancies is a snapshot of that
   same list, taken at analysis time (deliberately not recomputed live —
   see the column's own docstring for why that's correct here, unlike
   TR-112/TR-123's live-recomputed debtor aggregates).

Hand-written, not autogenerated — two plain add_column statements.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd3f7a1c9b2e4'
down_revision: Union[str, None] = 'c8e4b6f2a3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('traites', sa.Column('domiciliation', sa.Text(), nullable=True))
    op.add_column(
        'traites',
        sa.Column('cross_field_discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    op.drop_column('traites', 'cross_field_discrepancies')
    op.drop_column('traites', 'domiciliation')
